# Generated by Django 3.2.10 on 2021-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortingUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortUrl', models.CharField(max_length=10)),
                ('normalUrl', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
